### ISSUE TITLE
Question about connection problems

### ISSUE THREAD

**Issue by FabiFNA** [EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading#10]
Neither the gameboy nor the Flipper recognise the connection. I've connected seemingly everything accordingly. If I'm wrong please correct me by the following pictures:
![IMG_2624](https://user-images.githubusercontent.com/64425534/236631383-b63c8183-b859-455d-aca2-e55150d45f27.JPG)

This is how it looks when it's attached to the Flipper:
![IMG_2623](https://user-images.githubusercontent.com/64425534/236631426-2f551864-4b13-462a-a0b9-d6c53d33bc77.JPG)

Just to clear things up, I've used a multimeter to check if everything is connected correctly and judging by the multimeter it is. None of the channels of the cable are connected to multiple GPIO ports. I've tried out an older version of the Flipper App and the newest release, neither worked. Also, using the 5V doesn't make any difference. Any ideas?

**Comment by EstebanFuentealba** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/442927/236646172-5e6c85ba-662e-431b-af5f-82beabab84e4.png)

Do not connect the 5v because you could kill the Gameboy or the flipper.

**Comment by FabiFNA** [comment]
Thank you very much that did the trick.
