### ISSUE TITLE
Funding Link

### ISSUE THREAD

**Issue by RogueMaster** [EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading#15]
### Describe the bug.

You don't have one, can you add one?

### Reproduction

See [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) for instructions

**Comment by EstebanFuentealba** [comment]
Great, thank you for the suggestion @RogueMaster , I've added it now.
