### ISSUE TITLE
feat: Add support for gen 2

### ISSUE THREAD

**Issue by sundhaug92** [EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading#16]
Could also mean support for IR gifts, which would mean it could act as an IR demo

**Comment by EstebanFuentealba** [comment]
This is one of the ideas that was proposed on Reddit. I believe it's possible, but I don't have a second-generation cartridge to test it.

**Comment by kbembedded** [comment]
FWIW this is on my roadmap but I want to get gen 1 fully fleshed out and in a state to make it easy to add in the next generation.

Part of the complication here is that gen 2 has a different trade structure, sort of. They did some really weird hacks to keep things compatible, but that is why Time Capsule exists in gen 2. (A really good writeup of it is here: https://jonstoler.me/blog/information-theory-pokemon). However, as it is now, the Flipper Pokemon Trading tool _should_ just work in gen 2 through the time capsule to trade in gen 1 pokemon. Adding gen 2 pokemon should be easy enough to just use a different trade struct.

IR mystery gifts would also be a great addition to this tool. That is not yet something on my roadmap, but once I start rolling out some of the new features I have planned, I can find a way to fold that support in.

**Comment by EstebanFuentealba** [comment]
Thank you, @kbembedded , for your contributions to the project. I'm eagerly looking forward to seeing those features.

**Comment by kbembedded** [comment]
Just for anyone who's watching this issue, I'm taking a bit of a hiatus to finally sit down and play through Gen I now that this tool has all of the features I want of it 😄 

I'll get to this eventually as I've got a copy of Gold that needs playing as well.

**Comment by kbembedded** [comment]
Initial gen ii support is implemented. Currently on a branch on my fork: https://github.com/kbembedded/Flipper-Zero-Game-Boy-Pokemon-Trading/tree/kris-add-genii

There is one outstanding issue that I'm aware of. If the flipper is on the WAITING screen and the gameboy is at the main trade interface after clicking on the table, if the flipper goes back one menu and re-enters trade now in the READY state, and the gameboy side tries to start a trade, the flipper does bad things and attempts to trade the same party member number from the gameboy. What should happen when the gameboy tries to trade with the flipper in this state, is the flipper should tell the gameboy to leave the trade table and force it to re-enter it and resync all of the states. Need to do some more work to fix that up.

What _is_ functional however, is, just about everything. Like gen i you can set:
Pokemon
Name
Level
Moves
(gen ii does _not_ trade type information, it is locked to the actual types)
EV/IV settings
OT name
OT ID

What is added as able to be set in gen ii:
All 251 pokemon trade-able
All moves in gen ii can be selected (though gen ii pokemon don't yet have their base moveset added yet)
Held item (you can set any valid item in the game, not just what pokemon are allowed to hold. Early bicycle anyone?)
Gender*
Shininess*
Unown's form*

(*) These are affected by IVs, changing one may affect the other. There is no current or planned support to try and make the flipper figure out how to meet any specific selections. e.g. Only two Unown forms can be shiny, if you set shiny it will change the form, if you change the form it will affect shiny.

This is still a WIP, I've not yet brought it in to the current PR as I want to clean up the aforementioned bug and still have other features to implement. However, if you have time/interest to do some testing, I'd love to get feedback on any issues now.

**Comment by sundhaug92** [comment]
Perhaps an idea if one uploaded some sort of signal capture so it was easier to test etc

**Comment by kbembedded** [comment]
> Perhaps an idea if one uploaded some sort of signal capture so it was easier to test etc

I'm not sure what you mean. Can you please clarify?

If you want, I can build and attach a .fap file, but I'm not sure how a logic analyzer capture of a trade would help with testing. I've got plenty and can upload one if you like, but it might be too large for GH to accept.

**Comment by sundhaug92** [comment]
I was thinking that with more eyes on the captures it'd be easier to decode etc

**Comment by kbembedded** [comment]
Sure. I've attached a couple below, one for gen i and one for gen ii. Note however, that this is between the GBC and flipper; I don't have a capture between two GBs and two copies of pokemon because I only have one GBC. So all of the the work I've done so far has been reverse engineering how trades work (they are surprisingly underdocumented) and testing.


[gen_i_blue_trade_edit_tradeback.zip](https://github.com/EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading/files/14471083/gen_i_blue_trade_edit_tradeback.zip)
[gen_ii_gold_trade_edit_tradeback.zip](https://github.com/EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading/files/14471084/gen_ii_gold_trade_edit_tradeback.zip)

Despite being named .zip, they are actually sigrok/pulseview session captures. Load them in to either of those.
