### ISSUE TITLE
Flipper not detected or connection closed

### ISSUE THREAD

**Issue by FoxLy1312** [EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading#2]
Instructions probably unclear 

trying to connect the pins directly to a cutted Link-Kabel. 

my question is : where the resistor supposed to get soldered to ? 

![6388AB10-0AD3-461B-8ECC-98C05F043B82](https://user-images.githubusercontent.com/110127890/227757177-7404371d-f236-4663-84e8-fe9016c8245c.jpeg)

**Comment by EstebanFuentealba** [comment]
Hi, I used 33k on CLK, but it's optional, it can be connected directly.

**Comment by EstebanFuentealba** [comment]
When you have the cable cut, test continuity with a voltmeter on the connector that goes to the Game Boy. **Game Link Cable** It's a crossover cable, so if on the Game Boy it's `SI` `SO`, on the Flipper Zero it should be `SO` `SI`.

![IMG-20230326-WA0003.jpg](https://user-images.githubusercontent.com/442927/227763496-16a75438-f834-41dc-aab9-f85bea9733ea.jpg)


In summary, try crossing those 2 wires

**Comment by EstebanFuentealba** [comment]
@FoxLy1312  Confirm if it helped you to close the issue or if not, to review what could be done. If it helped you, please share the images with your GBA 👍.

**Comment by FoxLy1312** [comment]
Combine all the suggestions dos the trick, thanks for the help, great work ♥️

![7145B528-2A53-4912-B8D9-C2DB87FEAEF2](https://user-images.githubusercontent.com/110127890/227800476-2d1e8dd2-a750-4246-90d7-7a16ba3e36dd.jpeg)
