### ISSUE TITLE
GPIO Pins Moved in RogueMaster Repo 

### ISSUE THREAD

**Issue by FoxLy1312** [EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading#5]
Connection Moved to:
SO (B3) -> A7
SI (B2) -> A6
CLK  (C3) ->  A4

unfortunately Ground stays GND 

Sorry for the nasty Glue, coloring from left to right is: 
orange, Red, Green, Blue 

![558474A6-72FA-47A1-AC70-8106E52627D4](https://user-images.githubusercontent.com/110127890/228988260-a135addb-f2ed-4e38-a52a-cf7db48776ee.jpeg)

**Comment by EstebanFuentealba** [comment]
I swapped the B2<->C3 pins and the problem was solved. https://github.com/EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading#connect-to-flipper-zero-without-socket-portdata-ext-link
